services:
  ielts-monitor:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ielts-appointment-monitor
    restart: unless-stopped
    
    # Volume mounts for persistent data and configuration
    volumes:
      # Configuration directory - allows runtime config changes
      - ./config:/app/config
      
      # Logs directory - persistent log storage
      - ./logs:/app/logs
      
      # Data directory - appointment tracking and notification history
      - ./data:/app/data
      
      # Environment file - read-only mount for security
      - ./.env:/app/.env:ro
    
    # Environment variables for Puppeteer containerized Chrome
    environment:
      # Production environment
      - NODE_ENV=production
      
      # Puppeteer Chrome configuration for container
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - CHROME_BIN=/usr/bin/chromium-browser
      - CHROME_PATH=/usr/bin/chromium-browser
      
      # Chrome flags for containerized environment
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--no-first-run,--no-zygote,--disable-gpu
    
    # Network configuration - default bridge network for external API access
    networks:
      - default
    
    # Port mapping for health check and potential web interface
    ports:
      - "3001:3002"
    
    # Optional health check (uncomment if needed)
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 120s
      timeout: 10s
      start_period: 30s
      retries: 3
    
    # Resource limits (uncomment and adjust as needed)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 256M

# Default network configuration
networks:
  default:
    driver: bridge

# Optional: Named volumes for better management (uncomment if preferred)
# volumes:
#   ielts_config:
#   ielts_logs:
#   ielts_data: